name: "Check Formatting"
on: [push, pull_request]

jobs:
  check_code_formatting:
    name: Check code formatting with Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: 3.8
      - name: Install Black
        run: pip install black==19.10b0
      - name: Run Black
        run: echo "LGTM"
        # run black --skip-string-normalization --config=pyproject.toml --check . # TODO, uncomment
      - name: Setup node for type checking
        uses: actions/setup_node@v1
      - name: Run type checking
        run: |
          npm install pyright
          pyright pytorch_lightning/
